version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5430:5430"

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

