version: '3.8'
services:  
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  web:
    build: .
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/Online-store
