version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  web:
    build: .
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/online-store
