version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    ports:
      - 127.0.0.1:9200:9200
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      discovery.type: single-node

  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
