version: '3.3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/Online-store
volumes:
  postgres: